<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>07_Promise的API</title>
</head>
<body>
  <!-- 
    1. Promise构造函数: new Promise (executor) {}
         executor函数: 同步执行(resolve, reject) => {}
         resolve函数: 调用resolve将Promise实例内部状态改为成功(resolved)。
         reject函数: 调用reject将Promise实例内部状态改为失败(rejected)。
         说明: excutor函数会在Promise内部立即同步调用,异步操作写在执行器中。

    2. Promise.prototype.then方法: Promise实例.then(onResolved, onRejected)
         onResolved: 成功的回调函数 (value) => {}
         onRejected: 失败的回调函数 (reason) => {}
         特别注意(难点)：then方法会返回一个新的Promise实例对象

    3. Promise.prototype.catch方法: Promise实例.catch(onRejected)
          onRejected: 失败的回调函数 (reason) => {}
          说明: catch方法是then方法的语法糖, 相当于: then(undefined, onRejected)

    4. Promise.resolve方法: Promisw.resolve(value)
          value可以为：1.成功的数据。2.一个新的Promise实例。
          说明: 用于快速返回一个状态为resolved或rejected的Promise实例对象

    5. Promise.reject方法: Promise.reject方法(reason)
          reason为失败的原因
          说明: 返回一个失败的Promise实例对象

    6. Promise.all方法: Promise.all(promiseArr)
          promiseArr: 包含n个Promise实例的数组
          说明: 返回一个新的Promise实例, 只有所有的promise都成功才成功, 只要有一个失败了就直接失败
				
    7. Promise.race方法: Promise.race(promiseArr)
          promiseArr: 包含n个Promise实例的数组
          说明: 返回一个新的Promise实例,最先出结果的promise的结果状态就是最终的结果状态
	-->
	<script type="text/javascript" >

    //1.观察then的返回值(不探讨具体返回Promise实例状态和数据的规则)
    /*let p1 = new Promise((resolve,reject)=>{
      resolve('成功的数据')
    })

    let x = p1.then(
      (value)=>{console.log('p1成功了',value)},
      (reason)=>{console.log('p1失败了',reason)}
    )
    console.log(x)*/

    //2.catch的使用
    //扩展：Promise实例如果指定了多组成功与失败的回调，都会调用吗----会
    /*let p1 = new Promise((resolve,reject)=>{
      setTimeout(()=>{
        reject('失败：xxx')
      },1000)
    })

    p1.catch(
      (reason)=>{console.log('失败2',reason)}
    )*/

    //3.Promise.resolve方法:用于快速返回一个Promise实例，状态可能成功，也可能失败
    //完整写法如下：
    /*let p1 = new Promise((resolve,reject)=>{
      resolve(900)
    })
    console.log(p1)*/
    //精简版写法如下：
    //let p1 = Promise.resolve(p0)

    //注意一个特殊的情况
    /*let p0 = new Promise((resolve,reject)=>{
      reject(800)
    })
    let p1 = Promise.resolve(p0)

    console.log(p1)*/

    //4.Promise.reject方法:用于快速返回一个Promise实例，状态必为失败。
    /*let p1 = new Promise((resolve,reject)=>{
      resolve(300)
    })
    let p2 = Promise.reject(p1)
    console.log(p2)*/

    //5.Promise.all方法
    /*let p1 = new Promise((resolve,reject)=>{
      setTimeout(()=>{
        reject('offer--1')
      },1000)
    })
    let p2 = Promise.resolve('1021')
    let p3 = Promise.resolve('atguigu')
    let p4 = new Promise((resolve,reject)=>{
      setTimeout(()=>{
        reject('offer---4')
      },4000)
    })


    let x = Promise.all([p4,p1,p2,p3])

    x.then(
      (value)=>{console.log('成功',value)},
      (reason)=>{console.log('失败',reason)}
    )*/

    //6.Promise.race
    /*let p1 = new Promise((resolve,reject)=>{
      setTimeout(()=>{
        reject('offer--1')
      },1000)
    })
    let p2 = Promise.reject('1021')
    let p3 = Promise.resolve('atguigu')
    let p4 = new Promise((resolve,reject)=>{
      setTimeout(()=>{
        reject('offer---4')
      },4000)
    })

    let x = Promise.race([p1,p2,p3,p4])

    x.then(
      (value)=>{console.log('成功',value)},
      (reason)=>{console.log('失败',reason)}
    )*/


	</script>
</body>
</html>