<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>10_async与await</title>
</head>
<body>
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
<script>
  /* 
  目标: 进一步掌握asyn/await的语法和使用
    1. async 函数
      函数的返回值为promise对象
      promise对象的结果由async函数执行的返回值决定,或看async函数是否抛出异常
   
    2. await 表达式
      await右侧的表达式一般为Promise实例对象, 但也可以是其它的值
      如果表达式是promise对象, await返回的是promise成功的值
      如果表达式是其它值, 直接将此值作为await的返回值
    
    3. 注意:
      await必须写在async函数中, 但async函数中可以没有await
      如果await的promise失败了, 就会抛出异常, 需要通过try...catch来捕获处理
  */


  //如何获取一个Promise实例的状态与值
  let p0 = new Promise((resolve,reject)=>{
    setTimeout(()=>{
      resolve('atguigu')
    },1000)
  })

  //第一种写法
  /*p0.then(
    (value)=>{console.log(value)},
    (reason)=>{console.log(reason)}
  )*/

  //第二种写法
  /*p0.then(
    (value)=>{console.log(value)}
  ).catch(
    (reason)=>{console.log(reason)}
  )*/

  //第三种写法
  /*(async()=>{
    try{
      let result = await p0
    }catch(err){
      console.log(err)
    }
  })()*/

  /***********************************************************/

  //终极解决方案：async配合await解决回调地狱
  /*function getData1() {
    return new Promise((resolve,reject)=>{
      $.get('https://api.apiopen.top/getTangPoetry?page=1&count=20',(data)=>{
        resolve(data)
      })
    })
  }
  function getData2() {
    return new Promise((resolve,reject)=>{
      $.get('https://api.apiopen.top/getJoke?page=1&count=2&type=video',(data)=>{
        setTimeout(()=>{
          resolve(data)
        },4000)
      })
    })
  }
  //demo方法有自己的逻辑，但是demo里面会用到getData1的数据、getData2的数据
  async function demo() {
    //demo函数要发请求，请求时会用到getData1、getData2的数据
    let value1
    let value2
    try{
      value1 = await getData1()
      value2 = await getData2()
    }catch(err){
      console.log(err)
    }
    console.log('发了最后一次请求',value1,value2)
  }
  demo()*/

</script>
</body>
</html>